version: '3.8'

services:
  clearproxy:
    image: ghcr.io/${GITHUB_REPOSITORY:-foggymtndrifter/clearproxy}:latest
    container_name: clearproxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./data/certificates:/certificates
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/clearproxy.db
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    driver: bridge 